language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 2.0.0
  - jruby-19mode
services:
  - mongodb
before_script:
  - mongo mydb_test --eval 'db.addUser("travis", "test");'
notifications:
  webhooks: http://dashbozu.herokuapp.com/hook/travisci
